apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Crane action test
on:
  workflow_dispatch:
jobs:
  build:
    steps:
      - name: Authenticate
        with:
          registry: https://hub.docker.com/
          username: gmaxey
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
        uses: cloudbees-io/configure-oci-credentials@v1
