apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: deploy_kind
on:
  workflow_dispatch:
jobs:
  deploy:
    environment: production
    steps:
      - name: Say hello
        kind: deploy
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
