apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Multi-artifact-build
on:
  workflow_dispatch:
    inputs:
      artifactName:
        type: string
      artifactVersion:
        type: string
jobs:
  build:
    steps:
      - name: generate sha
        id: sha
        uses: docker://alpine:3.18
        run: |
          echo "${{ inputs.artifactName }}:${{inputs.artifactVersion}}-${{ cloudbees.version }}" | sha256sum | awk '{print "sha256:"$1}' >> $CLOUDBEES_OUTPUTS/sha
      - uses: cloudbees-io/register-build-artifact@v1
        name: Publish artifact
        with:
          name: "${{ inputs.artifactName }}"
          version: "${{inputs.artifactVersion}}-${{ cloudbees.version }}"
          url: "https://docker.io/MyApp/${{ inputs.artifactName }}:${{inputs.artifactVersion}}-${{ cloudbees.version }}"
          digest: "${{ steps.sha.outputs.sha }}"
