apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: register deployment with parameter
on:
  workflow_dispatch:
    inputs:
      env:
        type: string
        default: gpm-qa
jobs:
  deploy:
    steps:
      - name: register deploy
        kind: deploy
        uses: cloudbees-io/register-deployed-artifact@main
        with:
          version: 5.7-0.0.588
          url: https://docker.io/MyApp/myComp:5.7-0.0.588
          target-environment: ${{ inputs.env }}
          name: myComp
