apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: register deployment with parameter
on:
  workflow_dispatch:
    inputs:
      env:
        type: string
        default: gpm-qa
jobs:
  build:
    steps:
      - name: register publish
        #kind: deploy
        uses: cloudbees-io/register-build-artifact@v1
        with:
          version: 7.23-0.0.553
          url: https://docker.io/myComp:7.23-0.0.553
          digest: sha256aa12344411840fa16466150c58f628dc6e6c40a9b07e3b3609
          #target-environment: ${{ inputs.env }}
          name: myComp
  deploy:
    steps:
      - name: register deploy
        kind: deploy
        uses: cloudbees-io/register-deployed-artifact@main
        with:
          version: 7.23-0.0.553
          url: https://docker.io/myComp:7.23-0.0.553
          digest: sha256aa12344411840fa16466150c58f628dc6e6c40a9b07e3b3609
          #target-environment: ${{ inputs.env }}
          name: myComp
    needs: build