apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: s3 upload test
on:
  workflow_dispatch:
jobs:
  build:
    steps:
      - name: Authenticate
        with:
          aws-region: west
        uses: cloudbees-io/configure-aws-credentials@v1
      - name: Push object to S3
        id: s3
        uses: cloudbees-io/s3-upload-object@v1
      - name: Use artifact ID
        run: echo ${{ steps.s3.outputs.artifact-id }}
        uses: docker://golang:1.20.3-alpine3.17
